from pylab import *

figure(figsize=(12, 10))
subplot(2, 2,1)
loss = loadtxt('loss.out')
loglog(loss[:,1:6])
loglog(loss[:,7:9])
xlabel('Generation/100')
ylabel('Loss')
legend(['Total', 'L1-regularization', 'L2-regularization', 'Energy-train', 'Force-train', 'Energy-test', 'Force-test'])
tight_layout()
#show()
#savefig('Loss.png',dpi=900)

subplot(2, 2,2)
energy_train = loadtxt('energy_train.out')
plot(energy_train[:, 1], energy_train[:, 0], '.')
plot(linspace(-7.2,-5.8), linspace(-7.2,-5.8), '-')
xlabel('DFT energy (eV/atom)')
ylabel('NEP energy (eV/atom)')
xlim(-7.2,-5.8)
ylim(-7.2,-5.8)
tight_layout()

subplot(2, 2,3)
force_train = loadtxt('force_train.out')
plot(force_train[:, 3:6], force_train[:, 0:3], '.')
plot(linspace(-27,31), linspace(-27,31), '-')
xlabel('DFT force (eV/A)')
ylabel('NEP force (eV/A)')
xlim(-27,31)
ylim(-27,31)
legend(['x direction', 'y direction', 'z direction'])
tight_layout()

subplot(2, 2,4)
stress = loadtxt('stress_train.out')
plot(stress[:, 6:9], stress[:, 0:3], '.')
# plot(linspace(0, 7), linspace(0, 7), '-')
xlabel('DFT stress (GPa)')
ylabel('NEP stress (GPa)')
# xlim(0, 7)
# ylim(0, 7)
legend(['xx direction', 'yy direction', 'zz direction'])
tight_layout()
#plt.show()
savefig('all-train-stress-1.png',dpi=600)
